config/routes.rb
begin
  Rails.application.routes.draw do
    cloudfuji_routes
  end
rescue => e
  puts "Error loading the Cloudfuji routes:"
  puts "#{e.inspect}"
end

Umi::Application.routes.draw do
  devise_for :users

  match "/events"                  => 'events#create',              :via => [:post, :get]
  match "/ido_share"               => 'events#script',              :as => 'script'
  match '/external'                => 'external#index'
  match '/external/:id'            => 'external#show'  
  match '/proxy'                   => 'external#proxy'
  match "/mailgun/notification"    => 'mailgun#notification',       :via => :post
  match "/mailchimp/notification"  => 'mailchimp#notification',     :via => :post
  match "/mailchimp/notification"  => 'mailchimp#confirm_webhook',  :via => :get
  match "/mailchimp/refresh_lists" => 'mailchimp#refresh_lists',    :via => :get
  match "/jenkins/notification"    => 'jenkins#notification',       :via => :post
  match "/stripe/received"         => 'stripe#received',            :via => :post
  match "/github/received"         => 'github#received',            :via => :post
  match "/pivotal/received"        => 'pivotal#received',           :via => :post
  match "/pivotal/import"          => 'pivotal#import',             :via => :get

  resources :auth_tokens 
  resource  :accounts 
  resources :imap_accounts, :only => [:create, :destroy]
  
  match '/' => 'accounts#index', :as => "root"
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
  before_filter :umi_authenticate_token!

  # POST /events
  # Incoming requests are expected to be authenticated with an API token
  # Requests MUST have a `category` and `name`
  def create
    respond_to do |format|
      if Ido::EventProcessor.process_and_fire!(current_user, JSON.parse(params[:event]))
        format.json { render :json => true, :status => 200}
      else
        format.json { render :json => false, :status => :unprocessable_entity }
      end
    end
  end


  def script
    @auth_token = current_user.auth_tokens.find_by_name("ido_share")

    response.headers["Last-Modified"] = Time.now.httpdate.to_s
    response.headers["Expires"] = 0.to_s

    # HTTP 1.0
    response.headers["Pragma"] = "no-cache"

    # HTTP 1.1 'pre-check=0, post-check=0' (IE specific)
    response.headers["Cache-Control"] = 'no-store, no-cache, must-revalidate, max-age=0, pre-check=0, post-check=0'
    response.headers['Content-type'] = 'application/javascript; charset=utf-8'

    respond_to do |format|
      format.js { return render :action => 'script', :layout => false, :content_type => 'text/javascript' }
    end
  end
end

app/helpers/events_helper.rb
module EventsHelper
end

app/views/events/script.html.erb
var IdoShare = (function(){
  if(typeof window.console === 'undefined'){
    window.console = {log: function(){return false;}};
  }

/*
* 
* TODO mixpanel old async library?
*
*/

  var auth_token = '<%= @auth_token.token  %>'
      ,endpoint_url = '//<%= request.host%><%= (request.port == 80) ? '' : ":#{request.port}" %><%= events_path %>.json'
      ,protocol = (document.location.protocol == 'https:' ? 'https:' : 'http:')
      ,all_deps = false
      ,async_log = []
      ,returned_api = {}
      ,api_inaction = false
      ,true_api = {
	  push: push
      }
      ,identity = (getCookie('idoShareId') == 'undefined') ? 'undefined' : getCookie('idoShareId')
      ;  


  function push(event_obj){
      if(typeof identity != 'undefined' && typeof identity != null){
	  event_obj.identity = identity;
      }

      var tag = document.createElement("script");
      tag.type = "text/javascript"; 
      tag.async = true;
      tag.defer = true;
      tag.src = protocol + endpoint_url+"?umi_token="+auth_token+"&event="+encodeURIComponent(JSON.stringify(event_obj));
      var s = document.getElementsByTagName("script")[0];
      s.parentNode.insertBefore(tag, s);
  }

    function setCookie(c_name,value,exdays){
	var exdate=new Date();
	exdate.setDate(exdate.getDate() + exdays);
	var c_value=escape(value) + ((exdays==null) ? "" : "; expires="+exdate.toUTCString());
	document.cookie=c_name + "=" + c_value;
    }

    function getCookie(c_name) {
	var x
	    ,y
	    ,ARRcookies=document.cookie.split(";")
	    ;

	for (var i=0; i<ARRcookies.length; i++) {
	    x=ARRcookies[i].substr(0,ARRcookies[i].indexOf("="));
	    y=ARRcookies[i].substr(ARRcookies[i].indexOf("=")+1);
	    x=x.replace(/^\s+|\s+$/g,"");
	    if (x==c_name)  {
		return unescape(y);
	    }
	}
    }

  function identify(uuid){
      setCookie(idoShareId, uuid);
      identity = uuid;
  }

  
  function checkForGA(){
    if(typeof window._gaq == 'undefined'){
	return false;
    }

    if(window._gaq.push != [].push){
	var old_meth = window._gaq.push
	window._gaq.push = function(){
	    var ido_event = {
		category: arguments[0][1]
		,name: arguments[0][2]
		,data : {
		    label: arguments[0][3]
		    ,value: arguments[0][4]
		}
	    };
	    
	    if(api_inaction = true){
		push(ido_event);
            }else{
		async_log.push(['push', ido_event]);
	    }
	    old_meth.apply(window._gaq, arguments);
	}
    }
  }


  function checkForMP(){
    var mp_api, old_meth;

    if(typeof window.mpq != 'undefined'){
	mp_api = window.mpq
    }else if(typeof window.mixpanel != 'undefined'){
	mp_api = window.mixpanel
    }else{
	return false;
    }

    if(typeof mp_api.track != 'undefined'){
	var old_meth = mp_api.track;
	mp_api.track = function(){
	    var ido_event = {
		category: "WebMetric"
		,name: arguments[0]
		,data : arguments[1]
	    };
	    if(api_inaction = true){
		push(ido_event);
            }else{
		async_log.push(['push', ido_event]);
	    }
	    old_meth.apply(window.mixpanel, arguments);
        }
    }

    if(typeof mp_api.identify != 'undefined'){
	var old_meth = mp_api.identify;
	mp_api.identify = function(){
	    if(api_inaction = true){
		push(arguments);
	    }else{
		async_log.push(['identify', arguments]);
	    }
	    old_meth.apply(window.mixpanel, arguments);
        }
    }

  }

  checkForGA();
  checkForMP();

  function loadDepJs(dep_url, cb){
    var s=document.createElement('script');
    s.setAttribute('type', "text/javascript");
    s.setAttribute('src', dep_url);
    head.appendChild(s);
    s.onload = function(){
      if(typeof cb === 'function'){
        cb();
      }
      scriptOnLoad();
    };

    s.onreadystatechange = function () {
      if (this.readyState === 'complete' || this.readyState === 'loaded'){
        if(typeof cb === 'function'){
          cb();
        }
        scriptOnLoad();
      }
    };
  }


  function executeBackLog(){
      if(api_inaction === false){
	  api_inaction = true;
	  var i;
	  for(i = 0; i<async_log.length; i++){
	      //call the method with given arguments
	      true_api[async_log[i][0]].apply(true_api, async_log[i][1]);	      
	  }
	  async_log = [];
      }
  }
   
  function returnTrueApi(){
    for(var value in true_api){
      returned_api[value] = true_api[value];
    }
    executeBackLog();
  }
   
   
  function scriptOnLoad(){
    if(typeof JSON === "undefined" || !JSON){
      return;
    }

    all_deps = true;
    if(api_inaction === false){
	returnTrueApi();
    }	
  }



  //If there is no jquery on the page load the latest
  if(typeof window.JSON === 'undefined' || !JSON){
    loadDepJs(protocol+'//cloudfuji.com/javascripts/easyXDM-2.4.15.118/json2.js');
  } 


  //call the onload incase all dependencies are met.
  scriptOnLoad();
      
  /*
   *
   * Return an api, depends on if dependencys are loaded or not
   *
   */
  return (function(){
    if(all_deps === true){
      return true_api;
    }else{
      for(prop in true_api){ (function(prop){
        returned_api[prop] = function(){
          async_log.push([prop, arguments]);
        };
      }(prop)); }
      return returned_api;
    }
  }());


})();