config/routes.rb
begin
  Rails.application.routes.draw do
    cloudfuji_routes
  end
rescue => e
  puts "Error loading the Cloudfuji routes:"
  puts "#{e.inspect}"
end

Umi::Application.routes.draw do
  devise_for :users

  match "/events"                  => 'events#create',              :via => [:post, :get]
  match "/ido_share"               => 'events#script',              :as => 'script'
  match '/external'                => 'external#index'
  match '/external/:id'            => 'external#show'  
  match '/proxy'                   => 'external#proxy'
  match "/mailgun/notification"    => 'mailgun#notification',       :via => :post
  match "/mailchimp/notification"  => 'mailchimp#notification',     :via => :post
  match "/mailchimp/notification"  => 'mailchimp#confirm_webhook',  :via => :get
  match "/mailchimp/refresh_lists" => 'mailchimp#refresh_lists',    :via => :get
  match "/jenkins/notification"    => 'jenkins#notification',       :via => :post
  match "/stripe/received"         => 'stripe#received',            :via => :post
  match "/github/received"         => 'github#received',            :via => :post
  match "/pivotal/received"        => 'pivotal#received',           :via => :post
  match "/pivotal/import"          => 'pivotal#import',             :via => :get

  resources :auth_tokens 
  resource  :accounts 
  resources :imap_accounts, :only => [:create, :destroy]
  
  match '/' => 'accounts#index', :as => "root"
end

app/controllers/accounts_controller.rb
class AccountsController < ApplicationController
  before_filter :authenticate_user!

  def index
    @auth_token = current_user.auth_tokens.where(:name => 'ido_share').first

    if @auth_token.nil?
      @auth_token = current_user.auth_tokens.create_new!(current_user, 'ido_share', 'IdoShare starter')
      puts "Auth token: #{@auth_token.inspect}"
      puts "errors: #{@auth_token.errors.inspect}"
    end

    %w(pivotal mailgun wufoo stripe github mailchimp).each do |service|
      instance_variable_set("@#{service}", current_user.settings_for(service))
    end

    @imap_accounts = IMAPAccount.where(:user_id => current_user.id).all
  end

  def create
    config = current_user.settings.find_or_create_by(:name => params[:name])
    if params['api_key'].present? || params['imap'] && params['imap']['password'].present?

      config.settings = params[params[:name]] if params[params[:name]]

      config.settings['api_key'] = params['api_key'] if params['api_key'].present?
      config.settings['human_name'] = params[:human_name] || params[:name]
      # Set data hash from name, if present (ie.g. 'imap')


      config.auth_token ||= current_user.auth_tokens.create!(:name => params[:name], :description => params[:name])
    else
      # Delete settings and auth token if api_key is blank
      config.settings = {}
      config.auth_token = nil
    end
    config.save

    puts "Config: #{config.inspect}"

    flash[:notice] = "Ok, updated #{config.settings['human_name']}!"
    puts "Config: #{config.inspect}"
    puts "Config: #{config.errors.inspect}"

    redirect_to root_url
  end
end

app/helpers/accounts_helper.rb
module AccountsHelper
end

app/views/accounts/index.html.erb
<h1>Services</h1>

<%= form_tag "/accounts" do %>
  <%= label_tag "Mailgun" %>
  <%= hidden_field_tag 'name', "mailgun" %>
  <%= text_field_tag "api_key", @mailgun.settings['api_key'] %>
  <%= submit_tag "Save", :class => 'button fat hot' %>
  <% if @mailgun.webhook_url %>
  <br/><br/>Use this as the mailgun webhook url: <%= link_to truncate(@mailgun.webhook_url, :length => 90), @mailgun.webhook_url %>
  <% end %>
<% end %>
<br/>

<%= form_tag "/accounts" do %>
  <%= label_tag "Pivotal" %>
  <%= hidden_field_tag 'name', "pivotal" %>
  <%= text_field_tag "api_key", @pivotal.settings['api_key'] %>
  <%= submit_tag "Save", :class => 'button fat hot' %>
  <% if @pivotal.settings['api_key'].present? %>
    | <%= link_to "Initial Import (may take awhile)", "/pivotal/import"  %>
  <% end %>
  <% if @pivotal.webhook_url %>
  <br/><br/>Use this as the Pivotal webhook url: <%= link_to truncate(@pivotal.webhook_url, :length => 90), @pivotal.webhook_url %>
  <% end %>
<% end %>
<br/>

<%= form_tag "/accounts" do %>
  <%= label_tag "Wufoo" %>
  <%= hidden_field_tag 'name', "wufoo" %>
  <%= text_field_tag "api_key", @wufoo.settings['api_key'] %>
  <%= submit_tag "Save", :class => 'button fat hot' %>
  <% if @wufoo.webhook_url %>
  <br/><br/>Use this as the Wufoo webhook url: <%= link_to truncate(@wufoo.webhook_url, :length => 90), @wufoo.webhook_url %>
  <% end %>

<% end %>
<br/>

<%= form_tag "/accounts" do %>
  <%= label_tag "Stripe" %>
  <%= hidden_field_tag 'name', "stripe" %>
  <%= text_field_tag "api_key", @stripe.settings['api_key'] %>
  <%= submit_tag "Save", :class => 'button fat hot' %>
  <% if @stripe.webhook_url %>
  <br/><br/>Use this as the Stripe webhook url: <%= link_to truncate(@stripe.webhook_url, :length => 90), @stripe.webhook_url %>
  <% end %>
<% end %>
<br/>

<%= form_tag "/accounts" do %>
  <%= label_tag "Mailchimp" %>
  <%= hidden_field_tag 'name', "mailchimp" %>
  <%= text_field_tag "api_key", @mailchimp.settings['api_key'] %>
  <%= submit_tag "Save", :class => 'button fat hot' %>
  <% if @mailchimp.settings['api_key'].present? %>
    | <%= link_to "Refresh cached Lists, Groupings & Groups", "/mailchimp/refresh_lists"  %>
  <% end %>
  <br/><br/>

  <% mailchimp_lists = current_user.mailchimp_lists %>
  <% if mailchimp_lists.none? %>
    No cached Mailchimp data.
  <% else %>
    <strong><a href="#mailchimp_lists" onclick="$('#mailchimp_lists').show(); $(this).hide();">Show cached Mailchimp lists</a></strong><br/>
    <div id="mailchimp_lists" style="display: none;">
    Key: <ul><li><strong>Lists</strong><ul><li><strong>Groupings</strong><ul><li><strong>Groups</strong></li></ul></li></ul></li></ul>
    <br/>
    <ul>
      <% current_user.mailchimp_lists.each do |list| %>
        <li><%= list.name %>
          <ul><% list.interest_groupings.each do |grouping| %>
            <li><%= grouping.name %>
              <ul><% grouping.interest_groups.each do |group| %>
                <li><%= group.name %></li>
              <% end %></ul>
            </li>
          <% end %></ul>
        </li>
      <% end %></ul>
    </div>
  <% end %>

  <% if @mailchimp.webhook_url %>
  <br/>Use this as the Mailchimp webhook url: <%= link_to truncate(@mailchimp.webhook_url, :length => 90), @mailchimp.webhook_url %>
  <% end %>
<% end %>
<br/>

<%= form_tag "/imap_accounts" do %>
  <%= label_tag "Gmail" %>
  <% if @imap_accounts.any? %>
    <p>Existing Accounts:</p>
    <ul>
    <% @imap_accounts.each do |account| %>
      <li>
      <%= account.server %>:<%= account.port %> |
      <%= account.email %> |
      Inbox folder: "<%= account.inbox_folder %>" |
      Sent folder: "<%= account.sent_mail_folder %>" |
      <%= link_to 'Delete?', imap_account_path(account.id), :method => :delete, :"data-confirm" => "Are you sure?" %>
      </li>
    <% end %>
    </ul>
    <br/>
  <% end %>
  <%= fields_for 'imap' do |f| %>
    <%= f.hidden_field 'server', :value => "imap.gmail.com" %>
    <%= f.hidden_field 'ssl', :value => "true" %>
    <%= f.hidden_field 'port', :value => "993" %>
    <%= f.hidden_field 'inbox_folder', :value => "Inbox" %>
    <%= f.hidden_field 'sent_mail_folder', :value => "[Gmail]/Sent Mail" %>
    
    <p>Add new account:</p>
    
    Email:
    <%= f.text_field "email" %>
    Password:
    <%= f.password_field "password" %>
  <% end %>
  <%= submit_tag "Save", :class => 'button fat hot' %>
<% end %>
<br/>

<p>
  <% if @github.webhook_url %>
  <br/>Use this as the GitHub webhook url: <%= link_to truncate(@github.webhook_url, :length => 90), @github.webhook_url %>
  <% end %>
</p>

<div id="custom_data" style="padding-top: 20px;">
  <h2>Custom data</h2>
  <h3>Include ido_share.js</h3>
  <p>Already using Google Analytics or Mixpanel? Great.</br>
    Just drop this IdoShare script into your page <strong>after those libraries</strong> and it will start collecting your existing events.</p>
 <pre>
  &lt;script type="text/javascript"&gt;Your Google Analytics Code&lt;/script&gt;
  &lt;script type="text/javascript"&gt;Your Mixpanel Code&lt;/script&gt;
  <strong>&lt;script type="text/javascript" src="<%= script_url %>.js"&gt;&lt;/script&gt;</strong>
</pre>

   <h3>Publishing events</h3>

<pre>
  &lt;script type="text/javascript" src="<%= script_url %>.js"&gt;&lt;/script&gt;
  <strong>&lt;script type="text/javascript" &gt;
    IdoShare.push({
      category: "IdoShare category"
      ,name: "IdoShare name"
      ,data: {} //javascript object with your data in.
    });
  &lt;/script&gt;
  </strong>
</pre>

</div>